### ISSUE TITLE
Please update the README file

### ISSUE THREAD

**Issue by okram999** [xebialabs-community/xld-github-dynamic-dictionaries-plugin#6]
Can you update the readme, so that: 

1. it shows a sample of the file that should be in github. 
I tried placing a file with the content 
{agentx=agentTST}, but it doesn't seem to like it. 

2. What if the repository is under a github org? Do we need to specify only the reponame or the "gitorg/reponame". Although this is a github library answer

**Comment by jdewinne** [comment]
1. The file expected in github should be a standard property file.
```
agentx=agentTST
agenty=agentQA
```
2. Currently the plugin doesn't support github organizations. If wanted, can you create a separate issue and/or pull request?
